import os
import io
import re
import json
import asyncio
import datetime
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, StreamingResponse, Response
from pydantic import BaseModel
from dotenv import load_dotenv
from fpdf import FPDF
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from orchestrator_agent import problem_agent, options_agent, risks_agent, recommendation_agent

load_dotenv()

app = FastAPI(title="ORQ Agent")
app.mount("/static", StaticFiles(directory="public"), name="static")


# ── Models ────────────────────────────────────────────────────────────────────

class QueryRequest(BaseModel):
    query: str


class ExportRequest(BaseModel):
    query: str
    problem: str
    options: str
    risks: str
    recommendation: str


# ── Helpers ───────────────────────────────────────────────────────────────────

def clean_markdown(text: str) -> str:
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s+', '', text)
    text = re.sub(r'^\s*[-*+]\s+', '- ', text, flags=re.MULTILINE)
    return text.strip()


def today() -> str:
    return datetime.datetime.now().strftime("%B %d, %Y")


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/")
async def root():
    return FileResponse("public/index.html")


@app.post("/analyze")
async def analyze(request: QueryRequest):
    query = request.query

    async def event_stream():
        try:
            yield f"data: {json.dumps({'event': 'stage_start', 'stage': 'problem'})}\n\n"
            problem = await asyncio.to_thread(problem_agent, query)
            yield f"data: {json.dumps({'event': 'stage_complete', 'stage': 'problem', 'content': problem})}\n\n"

            yield f"data: {json.dumps({'event': 'stage_start', 'stage': 'options'})}\n\n"
            options = await asyncio.to_thread(options_agent, query, problem)
            yield f"data: {json.dumps({'event': 'stage_complete', 'stage': 'options', 'content': options})}\n\n"

            yield f"data: {json.dumps({'event': 'stage_start', 'stage': 'risks'})}\n\n"
            risks = await asyncio.to_thread(risks_agent, query, problem, options)
            yield f"data: {json.dumps({'event': 'stage_complete', 'stage': 'risks', 'content': risks})}\n\n"

            yield f"data: {json.dumps({'event': 'stage_start', 'stage': 'recommendation'})}\n\n"
            recommendation = await asyncio.to_thread(recommendation_agent, query, problem, options, risks)
            yield f"data: {json.dumps({'event': 'stage_complete', 'stage': 'recommendation', 'content': recommendation})}\n\n"

            yield f"data: {json.dumps({'event': 'done'})}\n\n"

        except Exception as e:
            yield f"data: {json.dumps({'event': 'error', 'message': str(e)})}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.post("/export/pdf")
async def export_pdf(request: ExportRequest):
    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Title ──
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 12, "EXECUTIVE BRIEF", align="C")
    pdf.ln(4)

    # ── Date ──
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(130, 130, 130)
    pdf.cell(0, 6, today(), align="C")
    pdf.ln(6)

    # ── Top rule ──
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(5)

    # ── Query ──
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 5, f"Query: {request.query}")
    pdf.ln(4)

    # ── Sections ──
    sections = [
        ("01  PROBLEM",        request.problem),
        ("02  OPTIONS",        request.options),
        ("03  RISKS",          request.risks),
        ("04  RECOMMENDATION", request.recommendation),
    ]

    for label, content in sections:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, label)
        pdf.ln(1)
        pdf.set_draw_color(180, 180, 180)
        pdf.set_line_width(0.2)
        pdf.line(20, pdf.get_y(), 190, pdf.get_y())
        pdf.ln(3)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 4.8, clean_markdown(content))
        pdf.ln(5)

    # ── Footer rule ──
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.3)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(160, 160, 160)
    pdf.cell(0, 5, "Generated by ORQ Agent · curiositylogic.cloud", align="C")

    pdf_bytes = bytes(pdf.output())
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=executive-brief.pdf"},
    )


@app.post("/export/docx")
async def export_docx(request: ExportRequest):
    doc = Document()

    # ── Page margins ──
    for section in doc.sections:
        section.top_margin    = Pt(50)
        section.bottom_margin = Pt(50)
        section.left_margin   = Pt(60)
        section.right_margin  = Pt(60)

    # ── Title ──
    title = doc.add_heading("EXECUTIVE BRIEF", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # ── Date ──
    date_p = doc.add_paragraph()
    date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_r = date_p.add_run(today())
    date_r.font.size = Pt(9)
    date_r.font.color.rgb = RGBColor(130, 130, 130)

    # ── Query ──
    q_p = doc.add_paragraph()
    q_r = q_p.add_run(f"Query: {request.query}")
    q_r.font.italic = True
    q_r.font.size = Pt(9)
    q_r.font.color.rgb = RGBColor(80, 80, 80)
    doc.add_paragraph()

    # ── Sections ──
    sections = [
        ("01  PROBLEM",        request.problem),
        ("02  OPTIONS",        request.options),
        ("03  RISKS",          request.risks),
        ("04  RECOMMENDATION", request.recommendation),
    ]

    for label, content in sections:
        h = doc.add_heading(label, level=2)
        h.runs[0].font.color.rgb = RGBColor(0, 0, 0)

        for line in clean_markdown(content).split("\n"):
            line = line.strip()
            if line:
                p = doc.add_paragraph(line)
                p.runs[0].font.size = Pt(9)
        doc.add_paragraph()

    # ── Footer ──
    footer = doc.sections[0].footer
    fp = footer.paragraphs[0]
    fp.text = f"Generated by ORQ Agent · curiositylogic.cloud · {today()}"
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in fp.runs:
        run.font.size = Pt(7)
        run.font.color.rgb = RGBColor(160, 160, 160)

    buf = io.BytesIO()
    doc.save(buf)
    return Response(
        content=buf.getvalue(),
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": "attachment; filename=executive-brief.docx"},
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
